# Generated by Django 2.1.7 on 2025-05-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_auto_20250517_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemslist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemslist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items_images/'),
        ),
    ]
