# Generated by Django 2.1.7 on 2025-05-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_auto_20250517_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemslist',
            name='category',
            field=models.CharField(choices=[('dairy', 'Mléčné výrobky'), ('vegetables', 'Ovoce a zelenina'), ('frozen', 'Mražené potraviny'), ('meal', 'Hotová jídla'), ('bread', 'Pečivo'), ('other', 'Ostatní')], default='other', max_length=20),
        ),
    ]
