# Generated by Django 2.1.7 on 2025-05-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_itemslist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='category',
            field=models.CharField(choices=[('dairy', 'DAIRY'), ('meat', 'MEAT & SEAFOOD'), ('fruits', 'FRUITS & VEGGIES'), ('frozen', 'FROZEN'), ('drinks', 'DRINKS'), ('others', 'OTHERS')], default='others', max_length=20),
        ),
    ]
